name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: JTest
      id: jtest
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: JTest
        setup-command: sudo apt-get update && sudo apt-get install -y default-jdk
        command: "./run.sh"
        input: ''
        expected-output: Hello World
        comparison-method: exact
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JTEST_RESULTS: "${{steps.jtest.outputs.result}}"
      with:
        runners: jtest
